[package]
org = "maryam"
name = "reviewed"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
# version = "1.3.0"
version = "1.2.1"

[[dependency]]
org = "maryamzi"
name = "city_data_client"
version = "0.1.0"
repository = "local"
